<?php

use Illuminate\Database\Seeder;

class AirportsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $airport_data = App\airports::create(['name' => "KABUL"]);
        $airport_data = App\airports::create(['name' => "ANCHORAGE INTL"]);
        $airport_data = App\airports::create(['name' => "ANCHORAGE ELMENDORF"]);


        $airport_data = App\airports::create(['name' => "COLD BAY"]);
        $airport_data = App\airports::create(['name' => "FAIRBANKS"]);
        $airport_data = App\airports::create(['name' => "SHEYMA"]);
        $airport_data = App\airports::create(['name' => "TIRANA"]);
        $airport_data = App\airports::create(['name' => "ADRAR"]);
        $airport_data = App\airports::create(['name' => "ALGIERS"]);
        $airport_data = App\airports::create(['name' => "ANNABA"]);
        $airport_data = App\airports::create(['name' => "CONSTANTINE"]);
        $airport_data = App\airports::create(['name' => "EL GOLEA"]);
        $airport_data = App\airports::create(['name' => "GHARDAIA"]);
        $airport_data = App\airports::create(['name' => "HASSI MESSAOUD"]);
        $airport_data = App\airports::create(['name' => "IN SALAH"]);
        $airport_data = App\airports::create(['name' => "ORAN"]);
        $airport_data = App\airports::create(['name' => "TAMANRASSET"]);
        $airport_data = App\airports::create(['name' => "ZARAZAITINE"]);
        $airport_data = App\airports::create(['name' => "LUANDA"]);
        $airport_data = App\airports::create(['name' => "BUENOS AIRES"]);
        $airport_data = App\airports::create(['name' => "COMODORO RIVADAVIA"]);
        $airport_data = App\airports::create(['name' => "CORDOBA"]);
        $airport_data = App\airports::create(['name' => "MAR DE PLATA"]);
        $airport_data = App\airports::create(['name' => "ASCENSION"]);
        $airport_data = App\airports::create(['name' => "ADELAIDE"]);
        $airport_data = App\airports::create(['name' => "ALICE SPRINGS"]);
        $airport_data = App\airports::create(['name' => "AVALON"]);
        $airport_data = App\airports::create(['name' => "BRISBANE"]);
        $airport_data = App\airports::create(['name' => "CAIRNS"]);
        $airport_data = App\airports::create(['name' => "CANBERRA"]);
        $airport_data = App\airports::create(['name' => "COOLANGATTA"]);
        $airport_data = App\airports::create(['name' => "DARWIN"]);
        $airport_data = App\airports::create(['name' => "KARRATHA"]);
        $airport_data = App\airports::create(['name' => "KATHERINE"]);
        $airport_data = App\airports::create(['name' => "MEEKATHARRA"]);
        $airport_data = App\airports::create(['name' => "MELBOURNE"]);
        $airport_data = App\airports::create(['name' => "MOUNT ISA"]);
        $airport_data = App\airports::create(['name' => "NORFOLK ISLAND"]);
        $airport_data = App\airports::create(['name' => "PEARCE"]);
        $airport_data = App\airports::create(['name' => "PERTH"]);
        $airport_data = App\airports::create(['name' => "PORT HEDLAND"]);
        $airport_data = App\airports::create(['name' => "ROCKHAMPTON"]);
        $airport_data = App\airports::create(['name' => "SYDNEY"]);
        $airport_data = App\airports::create(['name' => "TOWNSVILLE"]);
        $airport_data = App\airports::create(['name' => "INNSBRUCK"]);
        $airport_data = App\airports::create(['name' => "KLAGENFURT"]);
        $airport_data = App\airports::create(['name' => "LINZ"]);
        $airport_data = App\airports::create(['name' => "SALZBURG"]);
        $airport_data = App\airports::create(['name' => "VIENNA"]);
        $airport_data = App\airports::create(['name' => "BAKU"]);
        $airport_data = App\airports::create(['name' => "LAJES"]);
        $airport_data = App\airports::create(['name' => "PONTA DELGARDO"]);
        $airport_data = App\airports::create(['name' => "SANTA MARIA"]);
        $airport_data = App\airports::create(['name' => "FREEPORT"]);
        $airport_data = App\airports::create(['name' => "NASSAU"]);
        $airport_data = App\airports::create(['name' => "BAHRAIN"]);
        $airport_data = App\airports::create(['name' => "CHITTAGONG"]);
        $airport_data = App\airports::create(['name' => "DHAKA TEZGAON"]);
        $airport_data = App\airports::create(['name' => "DHAKA INTL"]);
        $airport_data = App\airports::create(['name' => "BARBADOS"]);
        $airport_data = App\airports::create(['name' => "MINSK"]);
        $airport_data = App\airports::create(['name' => "ANTWERP"]);
        $airport_data = App\airports::create(['name' => "BRUSSELS"]);
        $airport_data = App\airports::create(['name' => "CHARLEROI"]);
        $airport_data = App\airports::create(['name' => "LIEGE"]);
        $airport_data = App\airports::create(['name' => "OSTEND"]);
        $airport_data = App\airports::create(['name' => "BELIZE"]);
        $airport_data = App\airports::create(['name' => "COTONOU"]);
        $airport_data = App\airports::create(['name' => "BERMUDA"]);
        $airport_data = App\airports::create(['name' => "FRANCISTOWN"]);
        $airport_data = App\airports::create(['name' => "GABORONE NOTWANE"]);
        $airport_data = App\airports::create(['name' => "GABORONE INTL"]);
        $airport_data = App\airports::create(['name' => "GHANZI"]);
        $airport_data = App\airports::create(['name' => "SELEBI-PHIKWE"]);
        $airport_data = App\airports::create(['name' => "BELO HORIZONTE"]);
        $airport_data = App\airports::create(['name' => "BRASILIA"]);
        $airport_data = App\airports::create(['name' => "CAMPINAS"]);
        $airport_data = App\airports::create(['name' => "FERNANDO DE NOROHNA"]);
        $airport_data = App\airports::create(['name' => "FLORIANPOLIS"]);
        $airport_data = App\airports::create(['name' => "MACEIO"]);
        $airport_data = App\airports::create(['name' => "NATAL"]);
        $airport_data = App\airports::create(['name' => "PORTO ALEGRE"]);
        $airport_data = App\airports::create(['name' => "RECIFE"]);
        $airport_data = App\airports::create(['name' => "RIO DE JANEIRO"]);
        $airport_data = App\airports::create(['name' => "SALVADOR"]);
        $airport_data = App\airports::create(['name' => "SAO JOSE DOS CAMPOS"]);
        $airport_data = App\airports::create(['name' => "SAO PAULO"]);
        $airport_data = App\airports::create(['name' => "BURGAS"]);
        $airport_data = App\airports::create(['name' => "SOFIA"]);
        $airport_data = App\airports::create(['name' => "VARNA"]);
        $airport_data = App\airports::create(['name' => "BOBO-DIOULASSO"]);
        $airport_data = App\airports::create(['name' => "OUAGADOUGOU"]);
        $airport_data = App\airports::create(['name' => "BUJUMBURA"]);
        $airport_data = App\airports::create(['name' => "PHNOM-PENH"]);
        $airport_data = App\airports::create(['name' => "DOUALA"]);
        $airport_data = App\airports::create(['name' => "GAROUA"]);
        $airport_data = App\airports::create(['name' => "YAOUNDE"]);
        $airport_data = App\airports::create(['name' => "ABBOTSFORD"]);
        $airport_data = App\airports::create(['name' => "BAGOTVILLE"]);
        $airport_data = App\airports::create(['name' => "CALGARY"]);
        $airport_data = App\airports::create(['name' => "CHURCHILL"]);
        $airport_data = App\airports::create(['name' => "EDMONTON"]);
        $airport_data = App\airports::create(['name' => "FREDERICTON"]);
        $airport_data = App\airports::create(['name' => "GANDER"]);
        $airport_data = App\airports::create(['name' => "GOOSE"]);
        $airport_data = App\airports::create(['name' => "HALIFAX"]);
        $airport_data = App\airports::create(['name' => "HALIFAX"]);
        $airport_data = App\airports::create(['name' => "HAMILTON"]);
        $airport_data = App\airports::create(['name' => "IQUALUIT"]);
        $airport_data = App\airports::create(['name' => "KUUJJUAG"]);
        $airport_data = App\airports::create(['name' => "MONCTON"]);
        $airport_data = App\airports::create(['name' => "MONT JOLI"]);
        $airport_data = App\airports::create(['name' => "MONTREAL DORVAL"]);
        $airport_data = App\airports::create(['name' => "MONTREAL MIRABEL"]);
        $airport_data = App\airports::create(['name' => "NORTH BAY"]);
        $airport_data = App\airports::create(['name' => "OTTAWA"]);
        $airport_data = App\airports::create(['name' => "QUEBEC"]);
        $airport_data = App\airports::create(['name' => "REGINA"]);
        $airport_data = App\airports::create(['name' => "SASSKATOON"]);
        $airport_data = App\airports::create(['name' => "SEPT ILES"]);
        $airport_data = App\airports::create(['name' => "ST. JOHNS"]);
        $airport_data = App\airports::create(['name' => "STEPHENVILLE"]);
        $airport_data = App\airports::create(['name' => "SYDNEY"]);
        $airport_data = App\airports::create(['name' => "THOMPSON"]);
        $airport_data = App\airports::create(['name' => "TORONTO"]);
        $airport_data = App\airports::create(['name' => "URANIUM CITY"]);
        $airport_data = App\airports::create(['name' => "VAL D'OR"]);
        $airport_data = App\airports::create(['name' => "VANCOUVER"]);
        $airport_data = App\airports::create(['name' => "WHITEHOUSE"]);
        $airport_data = App\airports::create(['name' => "WINDSOR"]);
        $airport_data = App\airports::create(['name' => "WINNIPEG"]);
        $airport_data = App\airports::create(['name' => "YARMOUTH"]);
        $airport_data = App\airports::create(['name' => "YELLOWKNIFE"]);
        $airport_data = App\airports::create(['name' => "FUERTEVENTURA"]);
        $airport_data = App\airports::create(['name' => "GRAN CANARIA"]);
        $airport_data = App\airports::create(['name' => "LA PALMA"]);
        $airport_data = App\airports::create(['name' => "LANZAROTE"]);
        $airport_data = App\airports::create(['name' => "TENERIFE NORTE"]);
        $airport_data = App\airports::create(['name' => "TENERIFE REINA SOFIA"]);
        $airport_data = App\airports::create(['name' => "SAL"]);
        $airport_data = App\airports::create(['name' => "GRAND CAYMAN"]);
        $airport_data = App\airports::create(['name' => "BAMGUI"]);
        $airport_data = App\airports::create(['name' => "CONCEPCION"]);
        $airport_data = App\airports::create(['name' => "PUNTA ARENAS"]);
        $airport_data = App\airports::create(['name' => "SANTIAGO"]);
        $airport_data = App\airports::create(['name' => "BEIJING"]);
        $airport_data = App\airports::create(['name' => "CHENGDU"]);
        $airport_data = App\airports::create(['name' => "GUANGZHOU/CANTON"]);
        $airport_data = App\airports::create(['name' => "KUNMING"]);
        $airport_data = App\airports::create(['name' => "LANZHOU"]);
        $airport_data = App\airports::create(['name' => "SHANGHAI"]);
        $airport_data = App\airports::create(['name' => "SHENZHEN"]);
        $airport_data = App\airports::create(['name' => "TAIYUAN"]);
        $airport_data = App\airports::create(['name' => "TIANJIN"]);
        $airport_data = App\airports::create(['name' => "URUMQI"]);
        $airport_data = App\airports::create(['name' => "XI'AN"]);
        $airport_data = App\airports::create(['name' => "BARRANQUILLA"]);
        $airport_data = App\airports::create(['name' => "BOGOTA"]);
        $airport_data = App\airports::create(['name' => "CALI"]);
        $airport_data = App\airports::create(['name' => "CARTEGENA"]);
        $airport_data = App\airports::create(['name' => "SAN ANDRES"]);
        $airport_data = App\airports::create(['name' => "DZAOUDZI"]);
        $airport_data = App\airports::create(['name' => "MORONI HAHAIA"]);
        $airport_data = App\airports::create(['name' => "MORONI ICONI"]);
        $airport_data = App\airports::create(['name' => "BRAZZAVILLE"]);
        $airport_data = App\airports::create(['name' => "POINTE NOIRE"]);
        $airport_data = App\airports::create(['name' => "DUBROVNIK"]);
        $airport_data = App\airports::create(['name' => "RIJEKA"]);
        $airport_data = App\airports::create(['name' => "SPLIT"]);
        $airport_data = App\airports::create(['name' => "ZADAR"]);
        $airport_data = App\airports::create(['name' => "ZAGREB"]);
        $airport_data = App\airports::create(['name' => "CAMAGUEY"]);
        $airport_data = App\airports::create(['name' => "CAYO LARGO DEL SUR"]);
        $airport_data = App\airports::create(['name' => "HAVANA"]);
        $airport_data = App\airports::create(['name' => "VARADERO"]);
        $airport_data = App\airports::create(['name' => "LARNACA"]);
        $airport_data = App\airports::create(['name' => "PAPHOS"]);
        $airport_data = App\airports::create(['name' => "PRAGUE"]);
        $airport_data = App\airports::create(['name' => "AALBORG"]);
        $airport_data = App\airports::create(['name' => "BILLUND"]);
        $airport_data = App\airports::create(['name' => "BORNHOLM"]);
        $airport_data = App\airports::create(['name' => "COPENHAGEN KASTRUP"]);
        $airport_data = App\airports::create(['name' => "COPENHAGEN ROSKILDE"]);
        $airport_data = App\airports::create(['name' => "ESBJERG"]);
        $airport_data = App\airports::create(['name' => "ODENSE"]);
        $airport_data = App\airports::create(['name' => "TIRSTRUP"]);
        $airport_data = App\airports::create(['name' => "DJIBOUTI"]);
        $airport_data = App\airports::create(['name' => "PUERTO PLATA"]);
        $airport_data = App\airports::create(['name' => "PUNTA CANA"]);
        $airport_data = App\airports::create(['name' => "SANTO DOMINGO"]);
        $airport_data = App\airports::create(['name' => "GUAYAQUIL"]);
        $airport_data = App\airports::create(['name' => "ALEXANDRIA"]);
        $airport_data = App\airports::create(['name' => "ASWAN"]);
        $airport_data = App\airports::create(['name' => "CAIRO"]);
        $airport_data = App\airports::create(['name' => "HURGHADA"]);
        $airport_data = App\airports::create(['name' => "LUXOR"]);
        $airport_data = App\airports::create(['name' => "PORT SAID"]);
        $airport_data = App\airports::create(['name' => "RAS EL NAKAB"]);
        $airport_data = App\airports::create(['name' => "RAS NASRANI"]);
        $airport_data = App\airports::create(['name' => "SAN SALVADOR"]);
        $airport_data = App\airports::create(['name' => "ADDIS ABABA"]);
        $airport_data = App\airports::create(['name' => "ASMARA"]);
        $airport_data = App\airports::create(['name' => "DIRE DAWA"]);
        $airport_data = App\airports::create(['name' => "HELSINKI MALMI"]);
        $airport_data = App\airports::create(['name' => "HELSINKI VANTAA"]);
        $airport_data = App\airports::create(['name' => "IVALO"]);
        $airport_data = App\airports::create(['name' => "MARIEHAMN"]);
        $airport_data = App\airports::create(['name' => "OULU"]);
        $airport_data = App\airports::create(['name' => "PORI"]);
        $airport_data = App\airports::create(['name' => "ROVANIEMI"]);
        $airport_data = App\airports::create(['name' => "TAMPERE"]);
        $airport_data = App\airports::create(['name' => "TURKU"]);
        $airport_data = App\airports::create(['name' => "ABBEVILLE"]);
        $airport_data = App\airports::create(['name' => "AGLEN"]);
        $airport_data = App\airports::create(['name' => "AJACCIO"]);
        $airport_data = App\airports::create(['name' => "ANGERS"]);
        $airport_data = App\airports::create(['name' => "BASLE"]);
        $airport_data = App\airports::create(['name' => "BASTIA"]);
        $airport_data = App\airports::create(['name' => "BERGERAC"]);
        $airport_data = App\airports::create(['name' => "BEUVAIS"]);
        $airport_data = App\airports::create(['name' => "BEZIERS"]);
        $airport_data = App\airports::create(['name' => "BIARRITZ/BAYONE"]);
        $airport_data = App\airports::create(['name' => "BORDEAUX"]);
        $airport_data = App\airports::create(['name' => "BREST"]);
        $airport_data = App\airports::create(['name' => "BRETIGNY-SUR-ORGE"]);
        $airport_data = App\airports::create(['name' => "CAEN"]);
        $airport_data = App\airports::create(['name' => "CAHORS"]);
        $airport_data = App\airports::create(['name' => "CALAIS-DUNKERQUE"]);
        $airport_data = App\airports::create(['name' => "CALVI"]);
        $airport_data = App\airports::create(['name' => "CAMBRAI"]);
        $airport_data = App\airports::create(['name' => "CANNES"]);
        $airport_data = App\airports::create(['name' => "CARCASSONNE"]);
        $airport_data = App\airports::create(['name' => "CHAMBERY"]);
        $airport_data = App\airports::create(['name' => "CHATEAUROUX"]);
        $airport_data = App\airports::create(['name' => "CHERBOURG"]);
        $airport_data = App\airports::create(['name' => "CLERMOUNT FERRAND"]);
        $airport_data = App\airports::create(['name' => "COLMAR"]);
        $airport_data = App\airports::create(['name' => "DEAUVILLE"]);
        $airport_data = App\airports::create(['name' => "DIEPPE"]);
        $airport_data = App\airports::create(['name' => "DIJON"]);
        $airport_data = App\airports::create(['name' => "DINARD"]);
        $airport_data = App\airports::create(['name' => "GRENOBLE"]);
        $airport_data = App\airports::create(['name' => "HYERES"]);
        $airport_data = App\airports::create(['name' => "LA ROCHELLE"]);
        $airport_data = App\airports::create(['name' => "LANNION"]);
        $airport_data = App\airports::create(['name' => "LE HAVRE"]);
        $airport_data = App\airports::create(['name' => "LE MANS"]);
        $airport_data = App\airports::create(['name' => "LE TOUQUET"]);
        $airport_data = App\airports::create(['name' => "LILLE"]);
        $airport_data = App\airports::create(['name' => "LIMOGES"]);
        $airport_data = App\airports::create(['name' => "LYON"]);
        $airport_data = App\airports::create(['name' => "MARSEILLE"]);
        $airport_data = App\airports::create(['name' => "METZ"]);
        $airport_data = App\airports::create(['name' => "MONTPELLIER"]);
        $airport_data = App\airports::create(['name' => "MORLAIX"]);
        $airport_data = App\airports::create(['name' => "NANCY"]);
        $airport_data = App\airports::create(['name' => "NANTES ATLANTIQUE"]);
        $airport_data = App\airports::create(['name' => "PARIS CHARLES DE GAULLE"]);
        $airport_data = App\airports::create(['name' => "PARIS LE BOURGET"]);
        $airport_data = App\airports::create(['name' => "PARIS ORLY"]);
        $airport_data = App\airports::create(['name' => "PAU PYRENEES"]);
        $airport_data = App\airports::create(['name' => "PERIGUEUX"]);
        $airport_data = App\airports::create(['name' => "PERPIGNAN"]);
        $airport_data = App\airports::create(['name' => "PONTOISE"]);
        $airport_data = App\airports::create(['name' => "QUIMPER"]);
        $airport_data = App\airports::create(['name' => "REIMS"]);
        $airport_data = App\airports::create(['name' => "RENNES"]);
        $airport_data = App\airports::create(['name' => "RODEZ"]);
        $airport_data = App\airports::create(['name' => "ROUEN"]);
        $airport_data = App\airports::create(['name' => "ST. BRIEUC"]);
        $airport_data = App\airports::create(['name' => "ST. ETTIENNE"]);
        $airport_data = App\airports::create(['name' => "ST. NAZAIRE"]);
        $airport_data = App\airports::create(['name' => "ST. YAN"]);
        $airport_data = App\airports::create(['name' => "STRASBOURG"]);
        $airport_data = App\airports::create(['name' => "TARBES"]);
        $airport_data = App\airports::create(['name' => "TOULOUSE BLAGNAC"]);
        $airport_data = App\airports::create(['name' => "TOULOUSE FRANCAZAL"]);
        $airport_data = App\airports::create(['name' => "TOURS"]);
        $airport_data = App\airports::create(['name' => "TOUSSUS LE NOBLE"]);
        $airport_data = App\airports::create(['name' => "TROYES"]);
        $airport_data = App\airports::create(['name' => "VALENCE"]);
        $airport_data = App\airports::create(['name' => "FRANCEVILLE"]);
        $airport_data = App\airports::create(['name' => "LIBREVILLE"]);
        $airport_data = App\airports::create(['name' => "PORT GENTIL"]);
        $airport_data = App\airports::create(['name' => "BANJUL"]);
        $airport_data = App\airports::create(['name' => "TBILISI"]);
        $airport_data = App\airports::create(['name' => "BERLIN GATOW"]);
        $airport_data = App\airports::create(['name' => "BERLIN SCHOENEFIELD"]);
        $airport_data = App\airports::create(['name' => "BERLIN TEGEL"]);
        $airport_data = App\airports::create(['name' => "BERLIN TEMPLEHOF"]);
        $airport_data = App\airports::create(['name' => "BRAUNSWEIG"]);
        $airport_data = App\airports::create(['name' => "BREMEN"]);
        $airport_data = App\airports::create(['name' => "COLOGNE-BONN"]);
        $airport_data = App\airports::create(['name' => "DORTMUND"]);
        $airport_data = App\airports::create(['name' => "DRESDEN"]);
        $airport_data = App\airports::create(['name' => "DUSSELDORF"]);
        $airport_data = App\airports::create(['name' => "ERFURT"]);
        $airport_data = App\airports::create(['name' => "FRANKFURT"]);
        $airport_data = App\airports::create(['name' => "FRIEDRICHSHAFEN"]);
        $airport_data = App\airports::create(['name' => "HAMBURG FINKENWERDER"]);
        $airport_data = App\airports::create(['name' => "HAMBURG"]);
        $airport_data = App\airports::create(['name' => "HANNOVER"]);
        $airport_data = App\airports::create(['name' => "INGOLSTADT"]);
        $airport_data = App\airports::create(['name' => "KASSEL-CALDEN"]);
        $airport_data = App\airports::create(['name' => "KIEL"]);
        $airport_data = App\airports::create(['name' => "LEIPZIG"]);
        $airport_data = App\airports::create(['name' => "LUBECK"]);
        $airport_data = App\airports::create(['name' => "MUNICH"]);
        $airport_data = App\airports::create(['name' => "MUNSTER"]);
        $airport_data = App\airports::create(['name' => "NORDHOLZ"]);
        $airport_data = App\airports::create(['name' => "NURNBERG"]);
        $airport_data = App\airports::create(['name' => "OBERPFAFFENHOFEN"]);
        $airport_data = App\airports::create(['name' => "PADERBORN"]);
        $airport_data = App\airports::create(['name' => "SAARBRUCKEN"]);
        $airport_data = App\airports::create(['name' => "STUTTGART"]);
        $airport_data = App\airports::create(['name' => "SYLT"]);
        $airport_data = App\airports::create(['name' => "ACCRA"]);
        $airport_data = App\airports::create(['name' => "KUMSAI"]);
        $airport_data = App\airports::create(['name' => "SUNYANI"]);
        $airport_data = App\airports::create(['name' => "TAKORADI"]);
        $airport_data = App\airports::create(['name' => "TAMALE"]);
        $airport_data = App\airports::create(['name' => "GIBRALTAR"]);
        $airport_data = App\airports::create(['name' => "ALEXANDROUPOLIS"]);
        $airport_data = App\airports::create(['name' => "ANDRAVIDA"]);
        $airport_data = App\airports::create(['name' => "ARAXOS"]);
        $airport_data = App\airports::create(['name' => "ATHENS"]);
        $airport_data = App\airports::create(['name' => "ELEFSIS"]);
        $airport_data = App\airports::create(['name' => "HERAKLION"]);
        $airport_data = App\airports::create(['name' => "IOANNINA"]);
        $airport_data = App\airports::create(['name' => "KARPATHOS"]);
        $airport_data = App\airports::create(['name' => "KAVALA"]);
        $airport_data = App\airports::create(['name' => "KEFALLINIA"]);
        $airport_data = App\airports::create(['name' => "KERKYRA"]);
        $airport_data = App\airports::create(['name' => "KHIOS"]);
        $airport_data = App\airports::create(['name' => "LIMNOS"]);
        $airport_data = App\airports::create(['name' => "MIKONOS"]);
        $airport_data = App\airports::create(['name' => "MITILINI"]);
        $airport_data = App\airports::create(['name' => "RHODES DIAGORAS"]);
        $airport_data = App\airports::create(['name' => "RHODES MARITSA"]);
        $airport_data = App\airports::create(['name' => "SALONIKA"]);
        $airport_data = App\airports::create(['name' => "SAMOS"]);
        $airport_data = App\airports::create(['name' => "SANTORINI"]);
        $airport_data = App\airports::create(['name' => "SKIATHOS"]);
        $airport_data = App\airports::create(['name' => "ZAKINTHOS"]);
        $airport_data = App\airports::create(['name' => "NARSARSUAQ"]);
        $airport_data = App\airports::create(['name' => "SONDERSTROM"]);
        $airport_data = App\airports::create(['name' => "GUATEMALA"]);
        $airport_data = App\airports::create(['name' => "BISSAU"]);
        $airport_data = App\airports::create(['name' => "CONAKRY"]);
        $airport_data = App\airports::create(['name' => "GEORGETOWN"]);
        $airport_data = App\airports::create(['name' => "HONOLULU"]);
        $airport_data = App\airports::create(['name' => "SAN PEDRO SULA"]);
        $airport_data = App\airports::create(['name' => "HONG KONG"]);
        $airport_data = App\airports::create(['name' => "BUDAPEST"]);
        $airport_data = App\airports::create(['name' => "AKUREYI"]);
        $airport_data = App\airports::create(['name' => "KEFLAVIK"]);
        $airport_data = App\airports::create(['name' => "REYKJAVIK"]);
        $airport_data = App\airports::create(['name' => "AHMEDABAD"]);
        $airport_data = App\airports::create(['name' => "BANGALORE"]);
        $airport_data = App\airports::create(['name' => "BOMBAY"]);
        $airport_data = App\airports::create(['name' => "CALCUTTA"]);
        $airport_data = App\airports::create(['name' => "DELHI"]);
        $airport_data = App\airports::create(['name' => "GOA"]);
        $airport_data = App\airports::create(['name' => "HYDERABAD"]);
        $airport_data = App\airports::create(['name' => "LUCKNOW"]);
        $airport_data = App\airports::create(['name' => "MADRAS"]);
        $airport_data = App\airports::create(['name' => "NAGPUR"]);
        $airport_data = App\airports::create(['name' => "PORT BLAIR"]);
        $airport_data = App\airports::create(['name' => "TRIVANDRUM"]);
        $airport_data = App\airports::create(['name' => "AMBON"]);
        $airport_data = App\airports::create(['name' => "BALI"]);
        $airport_data = App\airports::create(['name' => "BIAK"]);
        $airport_data = App\airports::create(['name' => "JAKARTA HALIM PERDANAKUSUMA"]);
        $airport_data = App\airports::create(['name' => "JAKARTA INTL"]);
        $airport_data = App\airports::create(['name' => "KUPANG"]);
        $airport_data = App\airports::create(['name' => "MEDAN"]);
        $airport_data = App\airports::create(['name' => "SURABAYA"]);
        $airport_data = App\airports::create(['name' => "UJUNG PANDANG"]);
        $airport_data = App\airports::create(['name' => "SHIRAZ"]);
        $airport_data = App\airports::create(['name' => "TABRIZ"]);
        $airport_data = App\airports::create(['name' => "TEHRAN"]);
        $airport_data = App\airports::create(['name' => "BAGHDAD"]);
        $airport_data = App\airports::create(['name' => "CONNAUGHT"]);
        $airport_data = App\airports::create(['name' => "CORK"]);
        $airport_data = App\airports::create(['name' => "DONEGAL"]);
        $airport_data = App\airports::create(['name' => "DUBLIN"]);
        $airport_data = App\airports::create(['name' => "GALWAY"]);
        $airport_data = App\airports::create(['name' => "KERRY"]);
        $airport_data = App\airports::create(['name' => "SHANNON"]);
        $airport_data = App\airports::create(['name' => "WATERFORD"]);
        $airport_data = App\airports::create(['name' => "JERUSALEM"]);
        $airport_data = App\airports::create(['name' => "OVDA"]);
        $airport_data = App\airports::create(['name' => "TEL AVIV"]);
        $airport_data = App\airports::create(['name' => "ALGHERO"]);
        $airport_data = App\airports::create(['name' => "ANCONA"]);
        $airport_data = App\airports::create(['name' => "BARI"]);
        $airport_data = App\airports::create(['name' => "BERGAMO"]);
        $airport_data = App\airports::create(['name' => "BOLOGNA"]);
        $airport_data = App\airports::create(['name' => "BRINDISI"]);
        $airport_data = App\airports::create(['name' => "CAGLIARI"]);
        $airport_data = App\airports::create(['name' => "CATANIA"]);
        $airport_data = App\airports::create(['name' => "FLORENCE"]);
        $airport_data = App\airports::create(['name' => "FORLI"]);
        $airport_data = App\airports::create(['name' => "GENOA"]);
        $airport_data = App\airports::create(['name' => "LAMEZIA TERME"]);
        $airport_data = App\airports::create(['name' => "MILAN LINATE"]);
        $airport_data = App\airports::create(['name' => "MILAN MALPENSA"]);
        $airport_data = App\airports::create(['name' => "NAPLES"]);
        $airport_data = App\airports::create(['name' => "OLBIA"]);
        $airport_data = App\airports::create(['name' => "PALERMO"]);
        $airport_data = App\airports::create(['name' => "PARMA"]);
        $airport_data = App\airports::create(['name' => "PESCARA"]);
        $airport_data = App\airports::create(['name' => "PISA"]);
        $airport_data = App\airports::create(['name' => "ABIDJAN"]);
        $airport_data = App\airports::create(['name' => "YAMOUSSOUKRO"]);
        $airport_data = App\airports::create(['name' => "KINGSTON"]);
        $airport_data = App\airports::create(['name' => "MONTEGO BAY"]);
        $airport_data = App\airports::create(['name' => "CHITOSE"]);
        $airport_data = App\airports::create(['name' => "FUKUOKA"]);
        $airport_data = App\airports::create(['name' => "HAKODATE"]);
        $airport_data = App\airports::create(['name' => "IWAKUNI"]);
        $airport_data = App\airports::create(['name' => "KAGOSHIMA"]);
        $airport_data = App\airports::create(['name' => "NAGASAKI"]);
        $airport_data = App\airports::create(['name' => "NAGOYA"]);
        $airport_data = App\airports::create(['name' => "OSAKA ITAMI"]);
        $airport_data = App\airports::create(['name' => "OSAKA KANSAI"]);
        $airport_data = App\airports::create(['name' => "SENDAI"]);
        $airport_data = App\airports::create(['name' => "TOKYO HANEDA"]);
        $airport_data = App\airports::create(['name' => "TOKYO NARITA"]);
        $airport_data = App\airports::create(['name' => "TOKYO YOKOTA"]);
        $airport_data = App\airports::create(['name' => "KISUMU"]);
        $airport_data = App\airports::create(['name' => "MALINDI"]);
        $airport_data = App\airports::create(['name' => "MOMBASA"]);
        $airport_data = App\airports::create(['name' => "NAIROBI"]);
        $airport_data = App\airports::create(['name' => "RIGA"]);
        $airport_data = App\airports::create(['name' => "MASERU"]);
        $airport_data = App\airports::create(['name' => "MONROVIA INTL"]);
        $airport_data = App\airports::create(['name' => "MONROVIA SPRIGGS PAYNE"]);
        $airport_data = App\airports::create(['name' => "BENGHAZI"]);
        $airport_data = App\airports::create(['name' => "KUFRA"]);
        $airport_data = App\airports::create(['name' => "SEBHA"]);
        $airport_data = App\airports::create(['name' => "TRIPOLI"]);
        $airport_data = App\airports::create(['name' => "VILNIUS"]);
        $airport_data = App\airports::create(['name' => "LUXEMBOURG"]);
        $airport_data = App\airports::create(['name' => "ANTANANARIVO"]);
        $airport_data = App\airports::create(['name' => "MAHAJANGA"]);
        $airport_data = App\airports::create(['name' => "ST. DENNIS"]);
        $airport_data = App\airports::create(['name' => "TOAMASINA"]);
        $airport_data = App\airports::create(['name' => "FUNCHAL"]);
        $airport_data = App\airports::create(['name' => "PORTO SANTO"]);
        $airport_data = App\airports::create(['name' => "BLANTYRE"]);
        $airport_data = App\airports::create(['name' => "KARONGA"]);
        $airport_data = App\airports::create(['name' => "LILONGWE"]);
        $airport_data = App\airports::create(['name' => "MZUZU"]);
        $airport_data = App\airports::create(['name' => "ALOR SETAR"]);
        $airport_data = App\airports::create(['name' => "BRUNEI INTL."]);
        $airport_data = App\airports::create(['name' => "JOHOR BAHRU"]);
        $airport_data = App\airports::create(['name' => "KOTA BHARU"]);
        $airport_data = App\airports::create(['name' => "KOTA KINBALU"]);
        $airport_data = App\airports::create(['name' => "KUALA LUMPUR"]);
        $airport_data = App\airports::create(['name' => "KUALA LUMPUR INTL."]);
        $airport_data = App\airports::create(['name' => "LABUAN"]);
        $airport_data = App\airports::create(['name' => "MALE INTL."]);
        $airport_data = App\airports::create(['name' => "MIRI"]);
        $airport_data = App\airports::create(['name' => "PENANG INTL."]);
        $airport_data = App\airports::create(['name' => "SIBU"]);
        $airport_data = App\airports::create(['name' => "TAWAU"]);
        $airport_data = App\airports::create(['name' => "BAMAKO"]);
        $airport_data = App\airports::create(['name' => "MOPTI"]);
        $airport_data = App\airports::create(['name' => "NIORO"]);
        $airport_data = App\airports::create(['name' => "TOMBOUCTOU"]);
        $airport_data = App\airports::create(['name' => "LUQA"]);
        $airport_data = App\airports::create(['name' => "NOUADHIBOU"]);
        $airport_data = App\airports::create(['name' => "NOUAKCHOTT"]);
        $airport_data = App\airports::create(['name' => "PLAISANCE"]);
        $airport_data = App\airports::create(['name' => "ACAPULCO"]);
        $airport_data = App\airports::create(['name' => "CAMPECHE"]);
        $airport_data = App\airports::create(['name' => "CANCUN"]);
        $airport_data = App\airports::create(['name' => "CHETUMAL"]);
        $airport_data = App\airports::create(['name' => "COZUMEL"]);
        $airport_data = App\airports::create(['name' => "GUADALAJARA"]);
        $airport_data = App\airports::create(['name' => "IXTAPA-ZIHUATANEJO"]);
        $airport_data = App\airports::create(['name' => "MERIDA"]);
        $airport_data = App\airports::create(['name' => "MEXICO CITY"]);
        $airport_data = App\airports::create(['name' => "TAMPICO"]);
        $airport_data = App\airports::create(['name' => "AGADIR"]);
        $airport_data = App\airports::create(['name' => "AL HOCEIMA"]);
        $airport_data = App\airports::create(['name' => "CASABLANCA ANFA"]);
        $airport_data = App\airports::create(['name' => "CASABLANCA INTL"]);
        $airport_data = App\airports::create(['name' => "LAAYOUNE"]);
        $airport_data = App\airports::create(['name' => "MARRAKECH"]);
        $airport_data = App\airports::create(['name' => "OUARZAZATE"]);
        $airport_data = App\airports::create(['name' => "OUJDA"]);
        $airport_data = App\airports::create(['name' => "RABAT"]);
        $airport_data = App\airports::create(['name' => "TANGIER"]);
        $airport_data = App\airports::create(['name' => "TETOUAN"]);
        $airport_data = App\airports::create(['name' => "BEIRA"]);
        $airport_data = App\airports::create(['name' => "INHAMBANE"]);
        $airport_data = App\airports::create(['name' => "MAPUTO"]);
        $airport_data = App\airports::create(['name' => "NAMPULA"]);
        $airport_data = App\airports::create(['name' => "TETE"]);
        $airport_data = App\airports::create(['name' => "VILANKULU"]);
        $airport_data = App\airports::create(['name' => "KATHMANDU"]);
        $airport_data = App\airports::create(['name' => "AMSTERDAM"]);
        $airport_data = App\airports::create(['name' => "EELDE"]);
        $airport_data = App\airports::create(['name' => "EINDHOVEN"]);
        $airport_data = App\airports::create(['name' => "LELYSTAD"]);
        $airport_data = App\airports::create(['name' => "MAASTRICHT"]);
        $airport_data = App\airports::create(['name' => "ROTTERDAM"]);
        $airport_data = App\airports::create(['name' => "AUCKLAND"]);
        $airport_data = App\airports::create(['name' => "CHRISTCHURCH"]);
        $airport_data = App\airports::create(['name' => "WELLINGTON"]);
        $airport_data = App\airports::create(['name' => "AGADES"]);
        $airport_data = App\airports::create(['name' => "NIAMEY"]);
        $airport_data = App\airports::create(['name' => "ZINDER"]);
        $airport_data = App\airports::create(['name' => "CALABAR"]);
        $airport_data = App\airports::create(['name' => "ENUGU"]);
        $airport_data = App\airports::create(['name' => "IBADAN"]);
        $airport_data = App\airports::create(['name' => "ILORIN"]);
        $airport_data = App\airports::create(['name' => "JOS"]);
        $airport_data = App\airports::create(['name' => "KADUNA"]);
        $airport_data = App\airports::create(['name' => "KANO"]);
        $airport_data = App\airports::create(['name' => "LAGOS"]);
        $airport_data = App\airports::create(['name' => "MAIDUGURI"]);
        $airport_data = App\airports::create(['name' => "PORT HAIRCOURT"]);
        $airport_data = App\airports::create(['name' => "SOKOTO"]);
        $airport_data = App\airports::create(['name' => "YOLA"]);
        $airport_data = App\airports::create(['name' => "ALESUND"]);
        $airport_data = App\airports::create(['name' => "BERGEN"]);
        $airport_data = App\airports::create(['name' => "FLORO"]);
        $airport_data = App\airports::create(['name' => "HARSTAD NARVIK"]);
        $airport_data = App\airports::create(['name' => "HAUGESUND"]);
        $airport_data = App\airports::create(['name' => "KIRKENES"]);
        $airport_data = App\airports::create(['name' => "KRISTIANSAND KJEVIK"]);
        $airport_data = App\airports::create(['name' => "KRISTIANSAND KVERNBERGET"]);
        $airport_data = App\airports::create(['name' => "OSLO FORNEBU"]);
        $airport_data = App\airports::create(['name' => "OSLO GARDERMOEN"]);
        $airport_data = App\airports::create(['name' => "STAVANGER"]);
        $airport_data = App\airports::create(['name' => "TORP"]);
        $airport_data = App\airports::create(['name' => "TROMSO"]);
        $airport_data = App\airports::create(['name' => "MUSCAT"]);
        $airport_data = App\airports::create(['name' => "SALALAH"]);
        $airport_data = App\airports::create(['name' => "ISLAMABAD"]);
        $airport_data = App\airports::create(['name' => "KARACHI"]);
        $airport_data = App\airports::create(['name' => "LAHORE"]);
        $airport_data = App\airports::create(['name' => "NAWABSHAH"]);
        $airport_data = App\airports::create(['name' => "PORT MORESBY"]);
        $airport_data = App\airports::create(['name' => "MACTAN"]);
        $airport_data = App\airports::create(['name' => "MANILA INTL."]);
        $airport_data = App\airports::create(['name' => "GDANSK"]);
        $airport_data = App\airports::create(['name' => "KRAKOW"]);
        $airport_data = App\airports::create(['name' => "POZNAN"]);
        $airport_data = App\airports::create(['name' => "WARSAW"]);
        $airport_data = App\airports::create(['name' => "FARO"]);
        $airport_data = App\airports::create(['name' => "LISBON"]);
        $airport_data = App\airports::create(['name' => "OPORTO"]);
        $airport_data = App\airports::create(['name' => "SAN JUAN"]);
        $airport_data = App\airports::create(['name' => "DOHA"]);
        $airport_data = App\airports::create(['name' => "BUCHAREST BANEASA"]);
        $airport_data = App\airports::create(['name' => "BUCHAREST OTOPENI"]);
        $airport_data = App\airports::create(['name' => "CONSTANTA"]);
        $airport_data = App\airports::create(['name' => "TIMISOARA"]);
        $airport_data = App\airports::create(['name' => "KHABARAOVSK"]);
        $airport_data = App\airports::create(['name' => "MOSCOW SHREMETIEVO"]);
        $airport_data = App\airports::create(['name' => "MOSCOW VNUKOVO"]);
        $airport_data = App\airports::create(['name' => "NOVOSIBIRSK"]);
        $airport_data = App\airports::create(['name' => "ORENBURG"]);
        $airport_data = App\airports::create(['name' => "SAMARA"]);
        $airport_data = App\airports::create(['name' => "ST. PETERSBURG"]);
        $airport_data = App\airports::create(['name' => "TVER"]);
        $airport_data = App\airports::create(['name' => "YAKUTSK"]);
        $airport_data = App\airports::create(['name' => "SAO TOME"]);
        $airport_data = App\airports::create(['name' => "ABHA"]);
        $airport_data = App\airports::create(['name' => "AL JOUF"]);
        $airport_data = App\airports::create(['name' => "ARAR"]);
        $airport_data = App\airports::create(['name' => "DHARAN"]);
        $airport_data = App\airports::create(['name' => "GASSIM"]);
        $airport_data = App\airports::create(['name' => "HAFR-AL-BATIN"]);
        $airport_data = App\airports::create(['name' => "HAIL"]);
        $airport_data = App\airports::create(['name' => "JEDDAH"]);
        $airport_data = App\airports::create(['name' => "MADINAH"]);
        $airport_data = App\airports::create(['name' => "RIYADH"]);
        $airport_data = App\airports::create(['name' => "TAIF"]);
        $airport_data = App\airports::create(['name' => "TURAIF"]);
        $airport_data = App\airports::create(['name' => "WEJH"]);
        $airport_data = App\airports::create(['name' => "DAKAR"]);
        $airport_data = App\airports::create(['name' => "SEYCHLLES"]);
        $airport_data = App\airports::create(['name' => "FREETOWN"]);
        $airport_data = App\airports::create(['name' => "SINGAPORE CHANGI"]);
        $airport_data = App\airports::create(['name' => "SINGAPORE PAYA LEBAR"]);
        $airport_data = App\airports::create(['name' => "BRATISLAVA"]);
        $airport_data = App\airports::create(['name' => "KOSICE"]);
        $airport_data = App\airports::create(['name' => "POPRAD"]);
        $airport_data = App\airports::create(['name' => "LJUBLJANA"]);
        $airport_data = App\airports::create(['name' => "MARIBOR"]);
        $airport_data = App\airports::create(['name' => "KISMAYU"]);
        $airport_data = App\airports::create(['name' => "MOGADISHU"]);
        $airport_data = App\airports::create(['name' => "BEAUFORT WEST"]);
        $airport_data = App\airports::create(['name' => "BETHLEHEM"]);
        $airport_data = App\airports::create(['name' => "BISHO"]);
        $airport_data = App\airports::create(['name' => "BLOEMFONTEIN"]);
        $airport_data = App\airports::create(['name' => "CAPE TOWN"]);
        $airport_data = App\airports::create(['name' => "DURBAN LOUIS BOTHA"]);
        $airport_data = App\airports::create(['name' => "DURBAN VIRGINIA"]);
        $airport_data = App\airports::create(['name' => "EAST LONDON"]);
        $airport_data = App\airports::create(['name' => "FICKSBURG"]);
        $airport_data = App\airports::create(['name' => "GEORGE"]);
        $airport_data = App\airports::create(['name' => "GIYANI"]);
        $airport_data = App\airports::create(['name' => "GRAHAMSTOWN"]);
        $airport_data = App\airports::create(['name' => "GRAND CENTRAL"]);
        $airport_data = App\airports::create(['name' => "GROOTFONTEIN"]);
        $airport_data = App\airports::create(['name' => "HEIDELBERG"]);
        $airport_data = App\airports::create(['name' => "HEILBRON"]);
        $airport_data = App\airports::create(['name' => "JOHANNESBURG INTL"]);
        $airport_data = App\airports::create(['name' => "JOHANNESBURG RAND"]);
        $airport_data = App\airports::create(['name' => "KEETMANSHOOP"]);
        $airport_data = App\airports::create(['name' => "KIGALI"]);
        $airport_data = App\airports::create(['name' => "KIMBERLEY"]);
        $airport_data = App\airports::create(['name' => "KLEINSEE"]);
        $airport_data = App\airports::create(['name' => "KOMATIPOORT"]);
        $airport_data = App\airports::create(['name' => "KROONSTAD"]);
        $airport_data = App\airports::create(['name' => "LADYSMITH"]);
        $airport_data = App\airports::create(['name' => "LANSERIA"]);
        $airport_data = App\airports::create(['name' => "LICHTENBURG"]);
        $airport_data = App\airports::create(['name' => "LUDERITZ"]);
        $airport_data = App\airports::create(['name' => "LYDENBURG"]);
        $airport_data = App\airports::create(['name' => "MALELANE"]);
        $airport_data = App\airports::create(['name' => "MARGATE"]);
        $airport_data = App\airports::create(['name' => "MESSINA"]);
        $airport_data = App\airports::create(['name' => "MMABATHO"]);
        $airport_data = App\airports::create(['name' => "NELSPRUIT"]);
        $airport_data = App\airports::create(['name' => "NEWCASTLE SA"]);
        $airport_data = App\airports::create(['name' => "OTJIWARONGO"]);
        $airport_data = App\airports::create(['name' => "PHALABORWA"]);
        $airport_data = App\airports::create(['name' => "PIET RETIEF"]);
        $airport_data = App\airports::create(['name' => "PIETERMARITZBURG"]);
        $airport_data = App\airports::create(['name' => "PIETERSBURG"]);
        $airport_data = App\airports::create(['name' => "PILANESBERG"]);
        $airport_data = App\airports::create(['name' => "PLETTENBERG BAY"]);
        $airport_data = App\airports::create(['name' => "PORT ELIZABETH"]);
        $airport_data = App\airports::create(['name' => "PRETORIA"]);
        $airport_data = App\airports::create(['name' => "QUEENSTOWN"]);
        $airport_data = App\airports::create(['name' => "RICHARDS BAY"]);
        $airport_data = App\airports::create(['name' => "SISHEN"]);
        $airport_data = App\airports::create(['name' => "THABA NCHU"]);
        $airport_data = App\airports::create(['name' => "ULUNDI"]);
        $airport_data = App\airports::create(['name' => "UPINGTON"]);
        $airport_data = App\airports::create(['name' => "VEREENIGING"]);
        $airport_data = App\airports::create(['name' => "VICTORIA WEST"]);
        $airport_data = App\airports::create(['name' => "VRYHEID"]);
        $airport_data = App\airports::create(['name' => "WELKOM"]);
        $airport_data = App\airports::create(['name' => "WINDHOEK EROS"]);
        $airport_data = App\airports::create(['name' => "WINDHOEK INTL"]);
        $airport_data = App\airports::create(['name' => "CHEJU"]);
        $airport_data = App\airports::create(['name' => "PUSAN"]);
        $airport_data = App\airports::create(['name' => "SEOUL"]);
        $airport_data = App\airports::create(['name' => "ALICANTE"]);
        $airport_data = App\airports::create(['name' => "ALMERIA"]);
        $airport_data = App\airports::create(['name' => "ASTURIAS"]);
        $airport_data = App\airports::create(['name' => "BARCELONA"]);
        $airport_data = App\airports::create(['name' => "BILBAO"]);
        $airport_data = App\airports::create(['name' => "CORDOBA"]);
        $airport_data = App\airports::create(['name' => "GERONA"]);
        $airport_data = App\airports::create(['name' => "GRANDA"]);
        $airport_data = App\airports::create(['name' => "IBIZA"]);
        $airport_data = App\airports::create(['name' => "JEREZ"]);
        $airport_data = App\airports::create(['name' => "LA CORUNA"]);
        $airport_data = App\airports::create(['name' => "MADRID BARAJAS"]);
        $airport_data = App\airports::create(['name' => "MADRID GETAFE"]);
        $airport_data = App\airports::create(['name' => "MALAGA"]);
        $airport_data = App\airports::create(['name' => "MINORCA"]);
        $airport_data = App\airports::create(['name' => "PALMA"]);
        $airport_data = App\airports::create(['name' => "PAMPLONA"]);
        $airport_data = App\airports::create(['name' => "REUS"]);
        $airport_data = App\airports::create(['name' => "SALAMANCA"]);
        $airport_data = App\airports::create(['name' => "SAN SEBASTIAN"]);
        $airport_data = App\airports::create(['name' => "SANTANDER"]);
        $airport_data = App\airports::create(['name' => "SANTIAGO"]);
        $airport_data = App\airports::create(['name' => "SEVILLE"]);
        $airport_data = App\airports::create(['name' => "VALENCIA"]);
        $airport_data = App\airports::create(['name' => "VIGO"]);
        $airport_data = App\airports::create(['name' => "VITORIA"]);
        $airport_data = App\airports::create(['name' => "COLOMBO INTL"]);
        $airport_data = App\airports::create(['name' => "COLOMBO RATMALANA"]);
        $airport_data = App\airports::create(['name' => "JAFFNA"]);
        $airport_data = App\airports::create(['name' => "GENEINA"]);
        $airport_data = App\airports::create(['name' => "JUBA"]);
        $airport_data = App\airports::create(['name' => "KHARTOUM"]);
        $airport_data = App\airports::create(['name' => "MATSAPHA"]);
        $airport_data = App\airports::create(['name' => "ANGELHOLM"]);
        $airport_data = App\airports::create(['name' => "BORLANGE"]);
        $airport_data = App\airports::create(['name' => "GOTHENBURG"]);
        $airport_data = App\airports::create(['name' => "JONKOPING"]);
        $airport_data = App\airports::create(['name' => "KALMAR"]);
        $airport_data = App\airports::create(['name' => "KARLSTAD"]);
        $airport_data = App\airports::create(['name' => "MALMO"]);
        $airport_data = App\airports::create(['name' => "MORA"]);
        $airport_data = App\airports::create(['name' => "NORKOPING"]);
        $airport_data = App\airports::create(['name' => "OREBRO"]);
        $airport_data = App\airports::create(['name' => "STOCKHOLM ARLANDA"]);
        $airport_data = App\airports::create(['name' => "STOCKHOLM BROMA"]);
        $airport_data = App\airports::create(['name' => "SUNDSVALL"]);
        $airport_data = App\airports::create(['name' => "UMEA"]);
        $airport_data = App\airports::create(['name' => "VISBY"]);
        $airport_data = App\airports::create(['name' => "BERNE"]);
        $airport_data = App\airports::create(['name' => "GENEVA"]);
        $airport_data = App\airports::create(['name' => "SION"]);
        $airport_data = App\airports::create(['name' => "ZURICH"]);
        $airport_data = App\airports::create(['name' => "DAMASCUS"]);
        $airport_data = App\airports::create(['name' => "KAOHSIUNG INTL."]);
        $airport_data = App\airports::create(['name' => "TAIPEI INTL."]);
        $airport_data = App\airports::create(['name' => "DAR ES SALAAM"]);
        $airport_data = App\airports::create(['name' => "KILIMANJARO"]);
        $airport_data = App\airports::create(['name' => "MTWARA"]);
        $airport_data = App\airports::create(['name' => "MWANZA"]);
        $airport_data = App\airports::create(['name' => "PEMBA"]);
        $airport_data = App\airports::create(['name' => "TABORA"]);
        $airport_data = App\airports::create(['name' => "TANGA"]);
        $airport_data = App\airports::create(['name' => "ZANZIBAR"]);
        $airport_data = App\airports::create(['name' => "N'DJAMENA"]);
        $airport_data = App\airports::create(['name' => "BANGKOK"]);
        $airport_data = App\airports::create(['name' => "CHIANG MAI"]);
        $airport_data = App\airports::create(['name' => "PHUKET"]);
        $airport_data = App\airports::create(['name' => "SONGKHLA"]);
        $airport_data = App\airports::create(['name' => "SURAT THANI"]);
        $airport_data = App\airports::create(['name' => "LOME"]);
        $airport_data = App\airports::create(['name' => "PORT OF SPAIN"]);
        $airport_data = App\airports::create(['name' => "SCARBOROUGH"]);
        $airport_data = App\airports::create(['name' => "JERBA"]);
        $airport_data = App\airports::create(['name' => "MONASTIR"]);
        $airport_data = App\airports::create(['name' => "SFAX"]);
        $airport_data = App\airports::create(['name' => "TOZEUR"]);
        $airport_data = App\airports::create(['name' => "TUNIS"]);
        $airport_data = App\airports::create(['name' => "ADANA"]);
        $airport_data = App\airports::create(['name' => "ANKARA"]);
        $airport_data = App\airports::create(['name' => "DALAMAN"]);
        $airport_data = App\airports::create(['name' => "ISTANBUL"]);
        $airport_data = App\airports::create(['name' => "IZMIR"]);
        $airport_data = App\airports::create(['name' => "ASHKHABAD"]);
        $airport_data = App\airports::create(['name' => "ENTEBBE"]);
        $airport_data = App\airports::create(['name' => "KIEV"]);
        $airport_data = App\airports::create(['name' => "LVOV"]);
        $airport_data = App\airports::create(['name' => "ODESSA"]);
        $airport_data = App\airports::create(['name' => "ABU DHABI"]);
        $airport_data = App\airports::create(['name' => "ABU DHABI"]);
        $airport_data = App\airports::create(['name' => "DUBAI"]);
        $airport_data = App\airports::create(['name' => "FUJAIRAH"]);
        $airport_data = App\airports::create(['name' => "RAS AL KHAIMAH"]);
        $airport_data = App\airports::create(['name' => "SHARJAH"]);
        $airport_data = App\airports::create(['name' => "ABERDEEN"]);
        $airport_data = App\airports::create(['name' => "ALDERNEY"]);
        $airport_data = App\airports::create(['name' => "ASCENSION IS."]);
        $airport_data = App\airports::create(['name' => "BARROW"]);
        $airport_data = App\airports::create(['name' => "BEDFORD"]);
        $airport_data = App\airports::create(['name' => "BELFAST"]);
        $airport_data = App\airports::create(['name' => "BELFAST"]);
        $airport_data = App\airports::create(['name' => "BEMBRIDGE"]);
        $airport_data = App\airports::create(['name' => "BENBECULA"]);
        $airport_data = App\airports::create(['name' => "BIGGIN HILL"]);
        $airport_data = App\airports::create(['name' => "BIRMINGHAM UK"]);
        $airport_data = App\airports::create(['name' => "BLACKBUSHE"]);
        $airport_data = App\airports::create(['name' => "BLACKPOOL"]);
        $airport_data = App\airports::create(['name' => "BOURNEMOUTH"]);
        $airport_data = App\airports::create(['name' => "BRISTOL"]);
        $airport_data = App\airports::create(['name' => "CAMBRIDGE"]);
        $airport_data = App\airports::create(['name' => "CARDIFF"]);
        $airport_data = App\airports::create(['name' => "CARLISLE"]);
        $airport_data = App\airports::create(['name' => "COVENTRY"]);
        $airport_data = App\airports::create(['name' => "CRANFIELD"]);
        $airport_data = App\airports::create(['name' => "DUNDEE"]);
        $airport_data = App\airports::create(['name' => "EAST MIDLANDS"]);
        $airport_data = App\airports::create(['name' => "EDINBURGH"]);
        $airport_data = App\airports::create(['name' => "EXETER"]);
        $airport_data = App\airports::create(['name' => "GLASGOW"]);
        $airport_data = App\airports::create(['name' => "GLOUCESTERSHIRE"]);
        $airport_data = App\airports::create(['name' => "GUERNSEY"]);
        $airport_data = App\airports::create(['name' => "HUMBERSIDE"]);
        $airport_data = App\airports::create(['name' => "INVERNESS"]);
        $airport_data = App\airports::create(['name' => "ISLAY"]);
        $airport_data = App\airports::create(['name' => "ISLE OF MAN"]);
        $airport_data = App\airports::create(['name' => "JERSEY"]);
        $airport_data = App\airports::create(['name' => "KIRKWALL"]);
        $airport_data = App\airports::create(['name' => "LEEDS BRADFORD"]);
        $airport_data = App\airports::create(['name' => "LIVERPOOL"]);
        $airport_data = App\airports::create(['name' => "LONDON CITY"]);
        $airport_data = App\airports::create(['name' => "LONDON GATWICK"]);
        $airport_data = App\airports::create(['name' => "LONDON HEATHROW"]);
        $airport_data = App\airports::create(['name' => "LONDON STANSTED"]);
        $airport_data = App\airports::create(['name' => "LUTON"]);
        $airport_data = App\airports::create(['name' => "LYDD"]);
        $airport_data = App\airports::create(['name' => "MANCHESTER"]);
        $airport_data = App\airports::create(['name' => "MANSTON"]);
        $airport_data = App\airports::create(['name' => "NEWCASTLE"]);
        $airport_data = App\airports::create(['name' => "OXFORD"]);
        $airport_data = App\airports::create(['name' => "PLYMOUTH"]);
        $airport_data = App\airports::create(['name' => "PRESTWICK"]);
        $airport_data = App\airports::create(['name' => "SOUTHAMPTOM"]);
        $airport_data = App\airports::create(['name' => "SOUTHEND"]);
        $airport_data = App\airports::create(['name' => "STORNOWAY"]);
        $airport_data = App\airports::create(['name' => "SUMBURGH"]);
        $airport_data = App\airports::create(['name' => "SWANSEA"]);
        $airport_data = App\airports::create(['name' => "TEESIDE"]);
        $airport_data = App\airports::create(['name' => "TIREE"]);
        $airport_data = App\airports::create(['name' => "UNST"]);
        $airport_data = App\airports::create(['name' => "WICK"]);
        $airport_data = App\airports::create(['name' => "ALBUQUERQUE"]);
        $airport_data = App\airports::create(['name' => "ATLANTA"]);
        $airport_data = App\airports::create(['name' => "ATLANTIC CITY"]);
        $airport_data = App\airports::create(['name' => "BALTIMORE"]);
        $airport_data = App\airports::create(['name' => "BANGOR"]);
        $airport_data = App\airports::create(['name' => "BEDFORD"]);
        $airport_data = App\airports::create(['name' => "BIRMINGHAM US"]);
        $airport_data = App\airports::create(['name' => "BOSTON"]);
        $airport_data = App\airports::create(['name' => "BUFFALO"]);
        $airport_data = App\airports::create(['name' => "BURLINGTON"]);
        $airport_data = App\airports::create(['name' => "CASPER"]);
        $airport_data = App\airports::create(['name' => "CENTRAL FLORIDA REGIONAL"]);
        $airport_data = App\airports::create(['name' => "CHARLESTON"]);
        $airport_data = App\airports::create(['name' => "CHARLOTTE"]);
        $airport_data = App\airports::create(['name' => "CHATTANOOGA"]);
        $airport_data = App\airports::create(['name' => "CHEYENNE"]);
        $airport_data = App\airports::create(['name' => "CHICAGO"]);
        $airport_data = App\airports::create(['name' => "CINCINNATI"]);
        $airport_data = App\airports::create(['name' => "CLEARWATER"]);
        $airport_data = App\airports::create(['name' => "CLEVELAND"]);
        $airport_data = App\airports::create(['name' => "COLARADO SPRINGS"]);
        $airport_data = App\airports::create(['name' => "COLUMBIA"]);
        $airport_data = App\airports::create(['name' => "COLUMBUS"]);
        $airport_data = App\airports::create(['name' => "DALLAS"]);
        $airport_data = App\airports::create(['name' => "DALLAS"]);
        $airport_data = App\airports::create(['name' => "DENVER"]);
        $airport_data = App\airports::create(['name' => "DES MOINES"]);
        $airport_data = App\airports::create(['name' => "DETROIT WAYNE"]);
        $airport_data = App\airports::create(['name' => "DETROIT WILLOW RUN"]);
        $airport_data = App\airports::create(['name' => "DULUTH"]);
        $airport_data = App\airports::create(['name' => "EVERETT"]);
        $airport_data = App\airports::create(['name' => "FARGO"]);
        $airport_data = App\airports::create(['name' => "FORT LAUDERDALE"]);
        $airport_data = App\airports::create(['name' => "FRESNO"]);
        $airport_data = App\airports::create(['name' => "GRAND JUNCTION"]);
        $airport_data = App\airports::create(['name' => "GREAT FALLS"]);
        $airport_data = App\airports::create(['name' => "HOUSTON"]);
        $airport_data = App\airports::create(['name' => "HUNTSVILLE"]);
        $airport_data = App\airports::create(['name' => "INDIANAPOLIS"]);
        $airport_data = App\airports::create(['name' => "JACKSONVILLE"]);
        $airport_data = App\airports::create(['name' => "KANSAS CITY INTL"]);
        $airport_data = App\airports::create(['name' => "KNOXVILLE"]);
        $airport_data = App\airports::create(['name' => "LAS VEGAS"]);
        $airport_data = App\airports::create(['name' => "LONG BEACH"]);
        $airport_data = App\airports::create(['name' => "LOS ANGELES"]);
        $airport_data = App\airports::create(['name' => "LOUISVILLE"]);
        $airport_data = App\airports::create(['name' => "MEMPHIS INTL"]);
        $airport_data = App\airports::create(['name' => "MIAMI"]);
        $airport_data = App\airports::create(['name' => "MILWAUKEE"]);
        $airport_data = App\airports::create(['name' => "MINNEAPOLIS"]);
        $airport_data = App\airports::create(['name' => "MONTGOMERY"]);
        $airport_data = App\airports::create(['name' => "MOSES LAKE"]);
        $airport_data = App\airports::create(['name' => "NASHVILLE"]);
        $airport_data = App\airports::create(['name' => "NEW ORLEANS"]);
        $airport_data = App\airports::create(['name' => "NEW YORK JOHN F. KENNEDY"]);
        $airport_data = App\airports::create(['name' => "NEW YORK LA GUARDIA"]);
        $airport_data = App\airports::create(['name' => "NEWARK"]);
        $airport_data = App\airports::create(['name' => "NEWBURGH"]);
        $airport_data = App\airports::create(['name' => "NEWPORT NEWS"]);
        $airport_data = App\airports::create(['name' => "NIAGARA FALLS"]);
        $airport_data = App\airports::create(['name' => "NORFOLK"]);
        $airport_data = App\airports::create(['name' => "OAKLAND"]);
        $airport_data = App\airports::create(['name' => "OMAHA"]);
        $airport_data = App\airports::create(['name' => "ONTARIO"]);
        $airport_data = App\airports::create(['name' => "ORLANDO"]);
        $airport_data = App\airports::create(['name' => "PHILADELPHIA"]);
        $airport_data = App\airports::create(['name' => "PHOENIX"]);
        $airport_data = App\airports::create(['name' => "PITTSBURGH"]);
        $airport_data = App\airports::create(['name' => "PORTLAND"]);
        $airport_data = App\airports::create(['name' => "PORTLAND"]);
        $airport_data = App\airports::create(['name' => "PRESSQUE ISLE"]);
        $airport_data = App\airports::create(['name' => "PUEBLO MEMORIAL"]);
        $airport_data = App\airports::create(['name' => "RENO"]);
        $airport_data = App\airports::create(['name' => "RICHMOND"]);
        $airport_data = App\airports::create(['name' => "SACRAMENTO"]);
        $airport_data = App\airports::create(['name' => "SALT LAKE CITY"]);
        $airport_data = App\airports::create(['name' => "SAN ANTONIO"]);
        $airport_data = App\airports::create(['name' => "SAN DIEGO"]);
        $airport_data = App\airports::create(['name' => "SAN FRANCISCO"]);
        $airport_data = App\airports::create(['name' => "SAVANNAH"]);
        $airport_data = App\airports::create(['name' => "SEATTLE"]);
        $airport_data = App\airports::create(['name' => "SEATTLE BOEING FIELD"]);
        $airport_data = App\airports::create(['name' => "SIOUX FALLS"]);
        $airport_data = App\airports::create(['name' => "SPOKANE INTL"]);
        $airport_data = App\airports::create(['name' => "ST. LOUIS"]);
        $airport_data = App\airports::create(['name' => "SYRACUSE"]);
        $airport_data = App\airports::create(['name' => "TAMPA"]);
        $airport_data = App\airports::create(['name' => "WASHINGTON DULLES"]);
        $airport_data = App\airports::create(['name' => "WASHINGTON NATIONAL"]);
        $airport_data = App\airports::create(['name' => "WEST PALM BEACH"]);
        $airport_data = App\airports::create(['name' => "WILMINGTON"]);
        $airport_data = App\airports::create(['name' => "WINDSOR LOCKS"]);
        $airport_data = App\airports::create(['name' => "MONTEVIDEO"]);
        $airport_data = App\airports::create(['name' => "SAMARKAND"]);
        $airport_data = App\airports::create(['name' => "TASHKENT"]);
        $airport_data = App\airports::create(['name' => "CARACAS"]);
        $airport_data = App\airports::create(['name' => "MARACAIBO"]);
        $airport_data = App\airports::create(['name' => "MARGARITA"]);
        $airport_data = App\airports::create(['name' => "DANANG"]);
        $airport_data = App\airports::create(['name' => "HANOI"]);
        $airport_data = App\airports::create(['name' => "HOCHIMINH"]);
        $airport_data = App\airports::create(['name' => "ST. LUCIA"]);
        $airport_data = App\airports::create(['name' => "ADEN"]);
        $airport_data = App\airports::create(['name' => "HODEIDAH"]);
        $airport_data = App\airports::create(['name' => "SANAA"]);
        $airport_data = App\airports::create(['name' => "TAIZ"]);
        $airport_data = App\airports::create(['name' => "BELGRADE"]);
        $airport_data = App\airports::create(['name' => "MOSTAR"]);
        $airport_data = App\airports::create(['name' => "OHRID"]);
        $airport_data = App\airports::create(['name' => "PODGORICA"]);
        $airport_data = App\airports::create(['name' => "SARAJEVO"]);
        $airport_data = App\airports::create(['name' => "SKOPJE"]);
        $airport_data = App\airports::create(['name' => "TIVAT"]);
        $airport_data = App\airports::create(['name' => "KINSHASA"]);
        $airport_data = App\airports::create(['name' => "KISANGANI"]);
        $airport_data = App\airports::create(['name' => "LUBUMBASHI"]);
        $airport_data = App\airports::create(['name' => "MBUJI-MAYI"]);
        $airport_data = App\airports::create(['name' => "KASAMA"]);
        $airport_data = App\airports::create(['name' => "LIVINGSTONE"]);
        $airport_data = App\airports::create(['name' => "LUSAKA"]);
        $airport_data = App\airports::create(['name' => "MANSA"]);
        $airport_data = App\airports::create(['name' => "MONGU "]);
        $airport_data = App\airports::create(['name' => "N'DOLA"]);
        $airport_data = App\airports::create(['name' => "BULAWAYO"]);
        $airport_data = App\airports::create(['name' => "CHIREDZI"]);
        $airport_data = App\airports::create(['name' => "HARARE"]);
        $airport_data = App\airports::create(['name' => "HARARE"]);
        $airport_data = App\airports::create(['name' => "HWANGE"]);
        $airport_data = App\airports::create(['name' => "KARIBA"]);
        $airport_data = App\airports::create(['name' => "MASVINGO"]);
        $airport_data = App\airports::create(['name' => "VICTORIA FALLS"]);
    }
}
